apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
        - name: to-do-app
          image: ramak873/to-do-app-assignment:0.0.3
          ports:
            - containerPort: 80
          imagePullPolicy: Always
--- 
apiVersion: v1
kind: Service
metadata:
  name: to-do-app
spec:
  selector:
    app: to-do-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004
  type: NodePort